file:
  upload-dir: uploads/images



server:
#  host: http://10.216.242.132:8082/api/v1
  port: 8082
#  address: 10.216.242.132
#  address: 10.0.200.7

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  application:
    name: foody

  datasource:
#    url: jdbc:postgresql://localhost:5432/foody
#    username: postgres
#    password: kimani89
     url: jdbc:postgresql://db.ufabksckowuvjzxxeqdr.supabase.co:5432/postgres?sslmode=require
     username: postgres
     password: $$@36878489Pk
     driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl_auto: update
    database: postgresql
    show_sql: true
